name: "Flutter & Shorebird Release GitHub Action"
description: "A GitHub Action to build and release Flutter applications with Shorebird integration."
author: "crazidev"

branding:
  icon: package
  color: green
  
inputs:
  # Flutter Build Inputs
  FLUTTER_VERSION:
    description: "Version of Flutter to use"
    required: true
    default: "3.29.3"
  FLUTTER_CHANNEL:
    description: "stable | main | beta: default is stable"
    required: true
    default: "stable"
  FLUTTER_BUILD_APK:
    description: "Set to true to build APK"
    required: false
    default: "false"
  FLUTTER_BUILD_AAB:
    description: "Set to true to build AAB"
    required: false
    default: "false"
  FLUTTER_BUILD_WEB:
    description: "Set to true to build for web"
    required: false
    default: "false"
  FLUTTER_EXTRA_ARGS:
    description: "Set to an additional arguments to pass to Flutter Build Command"
    required: false
    default: ""

  # Shorebird Release Inputs
  SHOREBIRD_RELEASE:
    description: "Set to true to perform a Shorebird release"
    required: false
    default: "false"
  SHOREBIRD_EXTRA_ARGS:
    description: "Set to an additional arguments to pass to Shorebird CLi"
    required: false
    default: ""
  SHOREBIRD_BUILD_IOS:
    description: "Set to true to build Shorebird for iOS"
    required: false
    default: "false"
  SHOREBIRD_BUILD_ANDROID:
    description: "Set to true to build Shorebird for Android"
    required: false
    default: "false"

  # Shorebird Patch Inputs
  SHOREBIRD_PATCH:
    description: "Set to true to apply Shorebird patch"
    required: false
    default: "false"
  SHOREBIRD_PATCH_RELEASE_VERSION:
    description: "Shorebird patch release version"
    required: false
    default: "1.0.0+4"
  SHOREBIRD_PATCH_ANDROID:
    description: "Set to true to apply Shorebird patch for Android"
    required: false
    default: "false"
  SHOREBIRD_PATCH_IOS:
    description: "Set to true to apply Shorebird patch for iOS"
    required: false
    default: "false"
    
  SHOREBIRD_TOKEN:
    description: "Shorebird token"
    required: false
    

  
  # Android Signing  
  ANDROID_KEYSTORE_BASE64:
    description: "Base64 encoded Android keystore file"
    required: false
  ANDROID_KEYSTORE_PASSWORD:
    description: "Password for Android keystore"
    required: false
  ANDROID_KEY_ALIAS:
    description: "Alias for Android key"
    required: false
  ANDROID_KEY_PASSWORD:
    description: "Password for Android key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Java
      if: ${{ inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.SHOREBIRD_BUILD_ANDROID == 'true' || inputs.SHOREBIRD_RELEASE == 'true' || inputs.SHOREBIRD_PATCH == 'true' }}
      uses: actions/setup-java@v4
      with:
        distribution: "oracle"
        cache: 'gradle'
        java-version: "17"

    - name: Set Up Flutter
      if: ${{ inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.FLUTTER_BUILD_WEB == 'true' || inputs.SHOREBIRD_RELEASE == 'true' || inputs.SHOREBIRD_PATCH == 'true' }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.FLUTTER_VERSION }}
        channel: ${{ inpts.FLUTTER_CHANNEL }}
        cache: true
  
    - name: Shorebird setup
      if: ${{ inputs.SHOREBIRD_RELEASE == 'true' || inputs.SHOREBIRD_PATCH == 'true' }}
      uses: shorebirdtech/setup-shorebird@v1

    - name: Install Dependencies
      if: ${{ inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.FLUTTER_BUILD_WEB == 'true' || inputs.SHOREBIRD_RELEASE == 'true' || inputs.SHOREBIRD_PATCH == 'true' }}
      run: flutter pub get
      shell: bash

    - name: Decode Keystore
      if: ${{ inputs.ANDROID_KEYSTORE_BASE64 && (inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.SHOREBIRD_BUILD_ANDROID == 'true') }}
      run: echo "${{ inputs.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > $HOME/keystore.jks
      shell: bash

    - name: Update key.properties
      if: ${{ inputs.ANDROID_KEYSTORE_BASE64 && (inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.SHOREBIRD_BUILD_ANDROID == 'true') }}
      run: |
        echo "storePassword=${{ inputs.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ inputs.ANDROID_KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ inputs.ANDROID_KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=$HOME/keystore.jks" >> android/key.properties
      shell: bash

    - name: Conditional apk build
      if: ${{ inputs.FLUTTER_BUILD_APK == 'true' }}
      run: flutter build apk --release ${{ inputs.FLUTTER_EXTRA_ARGS }}
      shell: bash

    - name: Conditional aab build
      if: ${{ inputs.FLUTTER_BUILD_AAB == 'true' }}
      run: flutter build appbundle ${{ inputs.FLUTTER_EXTRA_ARGS }}
      shell: bash

    - name: Conditional web build
      if: ${{ inputs.FLUTTER_BUILD_WEB == 'true' }}
      run: flutter build web ${{ inputs.FLUTTER_EXTRA_ARGS }}
      shell: bash

    - name: Conditional Shorebird Patch Android Step
      if: ${{ inputs.SHOREBIRD_PATCH == 'true' && inputs.SHOREBIRD_PATCH_ANDROID == 'true' }}
      uses: shorebirdtech/shorebird-patch@v1
      env:
        SHOREBIRD_TOKEN: ${{ inputs.SHOREBIRD_TOKEN }}
      with:
        platform: android
        args: "--release-version=${{ inputs.SHOREBIRD_PATCH_RELEASE_VERSION }} --allow-native-diffs --allow-asset-diffs ${{ inputs.SHOREBIRD_EXTRA_ARGS }}"

    - name: Conditional Shorebird Patch IOS Step
      if: ${{ inputs.SHOREBIRD_PATCH == 'true' && inputs.SHOREBIRD_PATCH_IOS == 'true' }}
      uses: shorebirdtech/shorebird-patch@v1
      env:
        SHOREBIRD_TOKEN: ${{ inputs.SHOREBIRD_TOKEN }}
      with:
        platform: ios
        args: "--release-version=${{ inputs.SHOREBIRD_PATCH_RELEASE_VERSION }} --allow-native-diffs --allow-asset-diffs ${{ inputs.SHOREBIRD_EXTRA_ARGS }}"

    - name: 🚀 Shorebird Release Android
      if: ${{ inputs.SHOREBIRD_RELEASE == 'true' && inputs.SHOREBIRD_BUILD_ANDROID == 'true' }}
      uses: shorebirdtech/shorebird-release@v1
      env:
        SHOREBIRD_TOKEN: ${{ inputs.SHOREBIRD_TOKEN }}
      with:
        platform: android
        args: "--flutter-version=${{ inputs.FLUTTER_VERSION }} ${{ inputs.SHOREBIRD_EXTRA_ARGS }}"

    - name: 🚀 Shorebird Release IOS
      if: ${{ inputs.SHOREBIRD_RELEASE == 'true' && inputs.SHOREBIRD_BUILD_IOS == 'true' }}
      uses: shorebirdtech/shorebird-release@v1
      env:
        SHOREBIRD_TOKEN: ${{ inputs.SHOREBIRD_TOKEN }}
      with:
        platform: ios
        args: "--flutter-version=${{ inputs.FLUTTER_VERSION }} ${{ inputs.SHOREBIRD_EXTRA_ARGS }}"

    - name: Upload Artifacts
      if: ${{ inputs.FLUTTER_BUILD_APK == 'true' || inputs.FLUTTER_BUILD_AAB == 'true' || inputs.FLUTTER_BUILD_WEB == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        if-no-files-found: ignore
        path: |
          build/app/outputs/flutter-apk/
          build/app/outputs/bundle/release/
          build/web/
